Add securityContext options to Helm Chart - Closes #97
kubernetes-sigs/nfs-subdir-external-provisioner pull request #105
Opened 2021-05-26 18:22 UTC by BYondRAK

Allow users to supply value overrides in the deployment to support podSecurtyContext and container securityContext.

2021-05-26 18:41 UTC, BYondRAK commented
/retitle Add securityContext options to Helm Chart - Resolves #97

2021-06-09 16:05 UTC, yonatankahana requested changes
hi,
when changing the helm chart, it is required to bump the helm chart version in the `Chart.yaml` as well, unless, the PR will be un-mergable since the tests will fail because every change in the helm chart triggers automatic chart version release once merged to `master`.

2021-08-04 15:45 UTC, yonatankahana commented
bump @BYondRAK :)

2021-10-03 20:41 UTC, yonatankahana commented
bump @BYondRAK :)
i will be very happy to merge that, can you please bump the chart version so it can be merged? thanks

2021-11-11 16:32 UTC, h0jeZvgoxFepBQ2C commented
bump @BYondRAK :)

2021-12-06 08:45 UTC, sidju commented
bump @BYondRAK :)
It'd help me a lot if this could be finished

2022-01-27 20:31 UTC, yonatankahana commented
completed in #171 thanks to @danieljkemp
/close

2022-01-27 20:32 UTC, closed without merging