PV provisioning fails when storageclass has volumeBindingMode as 'WaitForFirstConsumer'
kubernetes-sigs/nfs-subdir-external-provisioner pull request #71
Opened 2021-03-10 05:35 UTC by khalsa-ji

Fixes #70 :

1. Adds RBAC permissions to get nodes in the cluster.
2. Bumps chart version.

2021-03-10 06:22 UTC, khalsa-ji commented
/assign @kmova

2021-03-13 14:23 UTC, yonatankahana requested changes

2021-03-13 14:23 UTC, yonatankahana commented on charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
> +  - apiGroups: [""]
same changes required in the [`deploy/`](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/deploy/objects/clusterrole.yaml) as well

2021-04-05 15:28 UTC, yonatankahana commented on charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
> +  - apiGroups: [""]
@khalsa-ji
bump

2021-04-29 19:14 UTC, yonatankahana commented
/lgtm

2021-04-29 19:16 UTC, merged

2021-04-29 19:17 UTC, yonatankahana commented
thank you for your contribution :)

2021-04-30 17:38 UTC, khalsa-ji commented
> thank you for your contribution :)

It is my pleasure to contribute to the project. :)
@yonatankahana : Thank you for reviewing the PR.